# Generated by Django 5.1.2 on 2026-07-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannerLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('lead', models.CharField(blank=True, default='', max_length=255)),
                ('tag', models.CharField(default='Team Unstoppable / 2027 Planner lead', max_length=255)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Planner lead',
                'verbose_name_plural': 'Planner leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
