# Generated by Django 5.1.2 on 2026-07-16 22:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_planner_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('primary_contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('primary_contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('intake_started', 'Onboarding in progress'), ('intake_complete', 'Onboarding complete'), ('kickoff_scheduled', 'Kickoff scheduled'), ('active_pilot', 'Active pilot'), ('evaluation', 'Evaluation'), ('decision', 'Go / no-go decision')], default='invited', max_length=32)),
                ('source', models.CharField(choices=[('invited', 'Invited by AiraMed'), ('self_serve', 'Self-serve link')], default='invited', max_length=20)),
                ('invite_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client organization',
                'verbose_name_plural': 'Client organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.JSONField(blank=True, default=dict)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='myApp.clientorganization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
